### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by chookity-pokk** [jnpn/vast#1]
I was looking to make my own Python to Elisp transpiler and stumbled upon this. Was wondering if there was any documentation to help me understand what's happening here?

**Comment by jnpn** [comment]
Hi, 

sadly there's next to none, and the code could enjoy some refactoring. But basically it's a recursive visit of the python AST (from the stdlib ast module) and emitting elisp code that would match the semantics for each node. I planned to generated an elisp python runtime .. but I couldn't finish.

Have you ever used the ast module ? if so you can jump to https://github.com/jnpn/vast/blob/master/vast/visitors/visitors.py#L112

it's the main transpiling class.

If you have any question feel free to ask, and if you go on with your own transpiler, please notify me, I'd be very curious what you come up with.

Regards

**Comment by chookity-pokk** [comment]
Sorry for the late response, I immediately got busy with classes. Does this have the ability to read Python files or is it all done via REPL?

**Comment by jnpn** [comment]
Hi,

I didn't expect you to still want to hack on this code. I watched your PR, it's nice, although.. I think I should clean up the codebase before you add stuff on it. I wrote it long ago without formatter/linter and there's a lot of dirt in it (as you saw) it's a bit of a shame (flake8 reports 100+ issues). 

Also I think the main logic is very fragile (the class compilation is not CLOS compliant), the lisp runtime for python types is still missing, so maybe it should be redesigned. Maybe it's worth making a fresh beta2 branch or something like that. 

Were you planning on having a serious tool to transpile python to elisp and would be interested in making an actual full fledged transpiler ?

See ya

ps: oh and btw, take all the time you need to study, I can wait :)

**Comment by chookity-pokk** [comment]
I actually started reformatting the code, but it seems like you are already working on that! 

I am really kinda looking to see how far this could go, so making it a more serious tool is kinda what I am looking to work towards. Though I've only ever made a single compiler and a single interpreter so I'm still fairly new to this type of stuff. 

Do you have an IRC handle or something where we can move the discussion to? Might be a bit easier than communicating via a GitHub issue tracker haha.

**Comment by jnpn** [comment]
Yeah we could use #vast chan on libera.chat (maybe find a better name later).

I wanted your PR to be only about new additions and not old formatting issues, it's cleaner to separate aspects. 

I also had a develop branch that I used to modernize the project structure. Do you think you could rebase your PR on this branch ? and use click instead of argparse (really sorry to tell you that now).

I'll be on #vast @ libera.chat , see ya there

**Comment by chookity-pokk** [comment]
Great! I believe I joined the chat so we'll continue to communicate there!
